const SENSITIVE_WORDS = [
  'fuck', 'shit', 'bitch', 'asshole', 'dick', 'pussy', 'nigger', 'cunt', 'damn', 'bastard',
  'bullshit', 'suck', 'piss', 'fucking', 'fucker', 'hell', 'son of a bitch', 'motherfucker',
  'holy shit', 'god damn', 'what the fuck', 'go to hell', 'bitch ass', 'dickhead', 'ass wipe',
  'cock', 'balls', 'tits', 'boobs', 'ass', 'damn it', 'damn you', 'bloody hell', 'arsehole',
  'wanker', 'prick', 'twat', 'slut', 'whore', 'crap', 'shithead', 'douchebag', 'jackass',
  'asshat', 'dumbass', 'assclown', 'scumbag', 'son of a gun', 'hell yeah', 'damn right',
  'what the hell', 'for fucks sake', 'goddamn', 'damnation', 'damned', 'hellish', 'in hell',
  'satan', 'devil', 'lap dance', 'oral sex', 'anal sex', 'vagina', 'penis', 'anus',
  'testicles', 'breasts', 'nipples', 'erection', 'orgasm', 'cum', 'semen', 'ejaculate',
  'masturbate', 'masturbation', 'sex', 'sexy', 'sexually', 'sexiness', 'intercourse',
  'sexual', 'sexuality', 'sexting', 'sex tape', 'sex act', 'sexual intercourse',
  'sexual activity', 'sexual content', 'porn', 'pornography', 'pornographic', 'xxx',
  'hardcore', 'softcore', 'erotic', 'erotica', 'kinky', 'fetish', 'bondage', 'dominance',
  'submission', 'BDSM', 'threesome', 'gangbang', 'orgy', 'swinger', 'polygamy', 'incest',
  'bestiality', 'pedophilia', 'child porn', 'child pornography', 'underage', 'minor',
  'teen sex', 'teen porn', 'rape', 'rapist', 'raped', 'sexual assault', 'sexual abuse',
  'molestation', 'molest', 'molested', 'grooming', 'groomed', 'predator', 'sex offender',
  'sex crime', 'obscene', 'obscenity', 'lewd', 'indecent', 'vulgar', 'explicit', 'graphic',
  'nude', 'nudity', 'naked', 'bare', 'exposed', 'unclothed', 'topless', 'bottomless',
  'full frontal', 'hard on', 'boner', 'hardcore porn', 'porn star', 'adult film',
  'adult content', 'adult website', 'cam girl', 'cam boy', 'webcam', 'live cam',
  'sex chat', 'sext', 'dirty talk', 'talk dirty', 'hot', 'horny', 'aroused', 'turn on',
  'turned on', 'turn off', 'turned off', 'foreplay', 'petting', 'kissing', 'making out',
  'hooking up', 'one night stand', 'booty call', 'friends with benefits', 'casual sex',
  'no strings attached', 'fuck buddy', 'sex partner', 'lover', 'mistress', 'gigolo',
  'call girl', 'escort', 'massage parlor', 'happy ending', 'hand job', 'blow job',
  'head', 'fellatio', 'cunnilingus', 'rimming', '69', 'sixty nine', 'doggy style',
  'missionary', 'cowgirl', 'reverse cowgirl', 'anal', 'rim job', 'handjob', 'blowjob',
  'rimjob', 'cumshot', 'creampie', 'facial', 'swallow', 'spit', 'gag', 'choke',
  'whip', 'spank', 'spanking', 'roleplay', 'costume', 'lingerie', 'underwear', 'thong',
  'panties', 'bra', 'stockings', 'garter', 'corset', 'bikini', 'swimsuit', 'pornhub',
  'xvideos', 'redtube', 'youporn', 'tube8', 'xnxx', 'jav', 'japanese porn', 'asian porn',
  'amateur porn', 'homemade porn', 'professional porn', 'celebrity porn', 'celebrity sex tape',
  'sex tape', 'leaked', 'leak', 'hack', 'hacked', 'nude leak', 'nude photos', 'private photos',
  'sextape', 'revenge porn', 'dox', 'doxxing', 'doxxed', 'swat', 'swatted', 'death threat',
  'threaten', 'threat', 'kill', 'murder', 'suicide', 'die', 'dead', 'death', 'assassinate',
  'assassination', 'terrorism', 'terrorist', 'terror', 'bomb', 'explosion', 'shoot', 'gun',
  'rifle', 'pistol', 'weapon', 'arms', 'ammo', 'ammunition', 'knife', 'blade', 'stab',
  'stabbing', 'slash', 'cut', 'wound', 'blood', 'gore', 'violence', 'violent', 'fight',
  'brawl', 'attack', 'attacker', 'victim', 'kidnap', 'kidnapping', 'abduct', 'abduction',
  'torture', 'tortured', 'torturing', 'hostage', 'ransom', 'extortion', 'blackmail',
  'bribe', 'corruption', 'fraud', 'scam', 'con', 'cheat', 'theft', 'steal', 'rob',
  'burglary', 'break in', 'vandalism', 'destruction', 'arson', 'fire', 'burn', 'arsonist',
  'drug', 'drugs', 'narcotics', 'illegal drugs', 'drug dealer', 'dealer', 'smuggle',
  'smuggling', 'trafficking', 'trafficker', 'cocaine', 'crack', 'heroin', 'meth',
  'methamphetamine', 'ecstasy', 'mdma', 'lsd', 'acid', 'weed', 'marijuana', 'cannabis',
  'pot', 'hash', 'hashish', 'opium', 'opioid', 'painkiller', 'pill', 'prescription drug',
  'drug abuse', 'addiction', 'addict', 'alcohol', 'drunk', 'intoxicated', 'binge drinking',
  'alcoholic', 'sobriety', 'rehab', 'rehabilitation', 'overdose', 'OD', 'death from overdose',
  'drug death', 'drug overdose', 'alcohol poisoning', 'drinking and driving', 'DUI',
  'DWI', 'drunk driving', 'reckless driving', 'hit and run', 'manslaughter', 'criminal',
  'crime', 'criminal record', 'arrest', 'arrested', 'police', 'cop', 'officer', 'detective',
  'investigation', 'investigate', 'evidence', 'forensic', 'court', 'trial', 'judge', 'jury',
  'verdict', 'conviction', 'convicted', 'sentence', 'prison', 'jail', 'correctional facility',
  'inmate', 'prisoner', 'parole', 'probation', 'bail', 'bond', 'lawyer', 'attorney',
  'legal', 'illegal', 'unlawful', 'against the law', 'violation', 'violate', 'felony',
  'misdemeanor', 'offense', 'offender', 'guilty', 'innocent', 'plea', 'plead',
  'guilty plea', 'not guilty', 'appeal', 'appealed', 'appealing', 'sentencing', 'sentenced',
  'incarcerated', 'incarceration', 'life sentence', 'death penalty', 'capital punishment',
  'execution', 'execute', 'executed', 'electric chair', 'lethal injection', 'hanging',
  'firing squad', 'gas chamber', 'suicide', 'commit suicide', 'suicidal', 'self-harm',
  'self injury', 'cutting', 'bulimia', 'anorexia', 'eating disorder', 'depression',
  'depressed', 'mental illness', 'psychosis', 'schizophrenia', 'bipolar', 'manic',
  'panic attack', 'anxiety', 'anxious', 'PTSD', 'trauma', 'traumatic', 'abuse', 'abused',
  'abusive', 'domestic violence', 'emotional abuse', 'physical abuse', 'sexual abuse',
  'child abuse', 'elder abuse', 'bullying', 'bully', 'bullied', 'harassment', 'harass',
  'harassed', 'stalking', 'stalker', 'stalked', 'cyberbullying', 'cyber bully',
  'online harassment', 'troll', 'trolling', 'flame war', 'hate speech', 'hate crime',
  'racism', 'racist', 'racial', 'discrimination', 'discriminate', 'prejudice', 'bigotry',
  'bias', 'sexism', 'sexist', 'homophobia', 'homophobic', 'transphobia', 'transphobic',
  'xenophobia', 'xenophobic', 'antisemitism', 'antisemitic', 'islamophobia', 'islamophobic',
  'misogyny', 'misogynistic', 'misandry', 'misandristic', 'ableism', 'ableist', 'ageism',
  'ageist', 'fat shaming', 'body shaming', 'shame', 'humiliate', 'humiliation', 'embarrass',
  'embarrassment', 'mock', 'mocking', 'ridicule', 'taunt', 'taunting', 'insult', 'insulting',
  'offensive', 'offense', 'hurtful', 'harmful', 'vicious', 'malicious', 'malevolent',
  'spiteful', 'cruel', 'mean', 'unkind', 'unpleasant', 'disgusting', 'repulsive',
  'objectionable', 'filthy', 'dirty', 'vulgar', 'crude', 'coarse', 'rough', 'harsh',
  'brutal', 'savage', 'ferocious', 'fierce', 'angry', 'rage', 'fury', 'wrath', 'hate',
  'hatred', 'loathing', 'detest', 'detestation', 'abhor', 'abhorrence', 'despise',
  'despicable', 'contempt', 'contemptible', 'scorn', 'scornful', 'disdain', 'disdainful',
  'outrage', 'outraged', 'indignation', 'indignant', 'resentment', 'resent', 'bitter',
  'bitterness', 'malice', 'venom', 'venomous', 'poison', 'poisonous', 'toxic', 'toxicity',
  'toxic behavior', 'gaslight', 'gaslighting', 'gaslighter', 'manipulate', 'manipulation',
  'manipulative', 'deceive', 'deception', 'deceptive', 'lie', 'liar', 'lying', 'false',
  'fraudulent', 'con artist', 'scammer', 'cheater', 'swindle', 'swindler', 'deceiver',
  'mislead', 'misleading', 'trick', 'trickster', 'hoax', 'hoaxer', 'phony', 'fake',
  'imposter', 'impostor', 'identity theft', 'identity fraud', 'phishing', 'phish', 'phisher',
  'spoof', 'spoofing', 'hacker', 'hacking', 'cyber attack', 'cyber security', 'data breach',
  'compromised', 'vulnerability', 'exploit', 'exploited', 'ransomware', 'malware', 'virus',
  'trojan', 'spyware', 'adware', 'botnet', 'DDoS', 'denial of service', 'brute force',
  'password crack', 'password hacking', 'social engineering', 'pretexting', 'baiting',
  'quishing', 'smishing', 'vishing', 'whaling', 'spear phishing', 'clone phishing',
  'email spoofing', 'domain spoofing', 'IP spoofing', 'DNS spoofing', 'ARP spoofing',
  'session hijacking', 'cookie theft', 'CSRF', 'XSS', 'SQL injection', 'command injection',
  'buffer overflow', 'zero-day', 'exploit kit', 'dark web', 'deep web', 'TOR', 'VPN',
  'proxy', 'anonymizer', 'encryption', 'decryption', 'cryptography', 'crypto', 'bitcoin',
  'blockchain', 'altcoin', 'cryptocurrency', 'ICO', 'initial coin offering', 'crypto scam',
  'ponzi scheme', 'pyramid scheme', 'investment scam', 'get rich quick', 'make money fast',
  'work from home', 'earn money online', 'online job', 'remote work', 'freelance',
  'gig economy', 'side hustle', 'passive income', 'affiliate marketing', 'MLM',
  'multi-level marketing', 'network marketing', 'recruit', 'recruitment', 'downline',
  'upline', 'binary options', 'forex', 'stock market', 'day trading', 'options trading',
  'crypto trading', 'pump and dump', 'insider trading', 'market manipulation', 'scam alert',
  'scam warning', 'avoid scams', 'report scam', 'scam prevention', 'fraud prevention',
  'identity protection', 'credit card fraud', 'wire fraud', 'bank fraud', 'check fraud',
  'insurance fraud', 'tax fraud', 'medicare fraud', 'medicaid fraud', 'healthcare fraud',
  'pharmaceutical fraud', 'drug fraud', 'food fraud', 'consumer fraud', 'telemarketing fraud',
  'internet fraud', 'email fraud', 'phone fraud', 'social media fraud', 'romance scam',
  'catfishing', 'fake profile', 'fake account', 'sock puppet', 'astroturfing', 'shilling',
  'bot', 'bot account', 'automated', 'spam', 'spamming', 'spammer', 'junk mail',
  'unsolicited', 'phishing email', 'spam email', 'spam call', 'robocall', 'telemarketing',
  'cold call', 'door to door', 'fake charity', 'charity scam', 'fundraising scam',
  'crowdfunding scam', 'Kickstarter scam', 'Indiegogo scam', 'fake review', 'paid review',
  'shill review', 'review manipulation', 'fake news', 'disinformation', 'misinformation',
  'propaganda', 'conspiracy', 'conspiracy theory', 'clickbait', 'headline manipulation',
  'editorial bias', 'media bias', 'censorship', 'freedom of speech', 'free speech',
  'hate speech', 'incitement', 'incite', 'incited', 'provoke', 'provocation', 'agitation',
  'agitate', 'agitated', 'riot', 'rioting', 'protest', 'demonstration', 'unrest',
  'civil unrest', 'revolution', 'rebellion', 'insurrection', 'coup', "coup d'etat",
  'overthrow', 'seize power', 'political unrest', 'social unrest', 'economic unrest',
  'strike', 'labor strike', 'work stoppage', 'boycott', 'sanction', 'embargo', 'blockade',
  'siege', 'occupation', 'eviction', 'foreclosure', 'homeless', 'homelessness', 'poverty',
  'poor', 'destitute', 'needy', 'charity', 'philanthropy', 'donation', 'fundraising',
  'crowdfunding', 'indiegogo', 'kickstarter', 'gofundme', 'patreon', 'ko-fi',
  'buy me a coffee', 'support me', 'subscribe', 'membership', 'premium', 'VIP', 'exclusive',
  'limited', 'rare', 'collectible', 'NFT', 'non-fungible token', 'digital art', 'crypto art',
  'metaverse', 'virtual reality', 'augmented reality', 'VR', 'AR', 'mixed reality', 'MR',
  'avatar', 'digital avatar', 'virtual world', 'online game', 'MMORPG', 'RPG', 'FPS',
  'MOBA', 'battle royale', 'gacha', 'loot box', 'pay to win', 'free to play',
  'subscription', 'microtransaction', 'in-game purchase', 'cosmetic', 'skin', 'emote',
  'dance', 'emoji', 'sticker', 'filter', 'effect', 'animation', 'motion', 'particle',
  'graphics', 'render', 'texture', 'model', 'mesh', 'rig', 'keyframe', 'tween',
  'interpolation', 'physics', 'collision', 'raycast', 'AI', 'artificial intelligence',
  'machine learning', 'deep learning', 'neural network', 'algorithm', 'data mining',
  'big data', 'analytics', 'predictive', 'recommendation', 'personalization', 'targeted',
  'tracking', 'cookie', 'pixel', 'metrics', 'KPI', 'conversion', 'optimization',
  'A/B testing', 'split testing', 'heatmap', 'session recording', 'user behavior',
  'funnel', 'retention', 'churn', 'engagement', 'traffic', 'SEO', 'search engine optimization',
  'SEM', 'search engine marketing', 'PPC', 'pay per click', 'display advertising',
  'social media marketing', 'influencer marketing', 'content marketing', 'email marketing',
  'newsletter', 'campaign', 'advertising', 'ad', 'sponsored', 'native ad', 'banner ad',
  'popup', 'popunder', 'interstitial', 'video ad', 'pre-roll', 'mid-roll', 'post-roll',
  'skippable', 'non-skippable', 'ad blocker', 'ad blocking', 'ad free', 'freemium',
  'trial', 'free trial', 'promo', 'promotion', 'discount', 'coupon', 'deal', 'sale',
  'clearance', 'flash sale', 'limited time', 'offer', 'special offer', 'bundle',
  'package', 'combo', 'upgrade', 'downgrade', 'cancel', 'refund', 'return', 'exchange',
  'warranty', 'guarantee', 'satisfaction guarantee', 'money back guarantee',
  'no questions asked', 'risk free', 'trial period', 'grace period', 'billing cycle',
  'subscription fee', 'membership fee', 'service fee', 'processing fee', 'transaction fee',
  'hidden fee', 'fine print', 'terms of service', 'terms and conditions', 'privacy policy',
  'cookie policy', 'GDPR', 'CCPA', 'data protection', 'privacy', 'security', 'SSL',
  'TLS', 'HTTPS', 'firewall', 'antivirus'
]

export function containsSensitiveWords(content) {
  if (!content || typeof content !== 'string') {
    return false
  }
  const lowerContent = content.toLowerCase()
  return SENSITIVE_WORDS.some(word => lowerContent.includes(word.toLowerCase()))
}

export function getSensitiveWords(content) {
  if (!content || typeof content !== 'string') {
    return []
  }
  const lowerContent = content.toLowerCase()
  return SENSITIVE_WORDS.filter(word => lowerContent.includes(word.toLowerCase()))
}